version: "3.8"

x-common-env: &common-env
  SERVER_SECRET: ${HULY_SECRET}
  SECRET: ${HULY_SECRET}
  STORAGE_CONFIG: minio|minio?accessKey=minioadmin&secretKey=minioadmin
  MONGO_URL: mongodb://mongodb:27017
  DB_URL: mongodb://mongodb:27017
  ACCOUNTS_URL: http://account:3000
  STATS_URL: http://stats:4900

services:
  # Reine Backend-Datenbank
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - db:/data/db
    networks:
      - internal-services

  # Reines Backend-Object-Storage
  minio:
    image: minio/minio:RELEASE.2025-05-01T00-00-00Z
    restart: unless-stopped
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - files:/data
    networks:
      - internal-services

  # Reines Backend-Such-Cluster
  elastic:
    image: elasticsearch:7.14.2
    restart: unless-stopped
    command: |
      ./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment
      /usr/local/bin/docker-entrypoint.sh eswrapper
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8082
    healthcheck:
      test: ["CMD-SHELL","curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"red\"'"]
      interval: 20s
      retries: 10
    networks:
      - internal-services

  # Business-Logik / Worker (intern + Projektnetz)
  rekoni:
    image: hardcoreeng/rekoni-service:${HULY_VERSION}
    restart: unless-stopped
    environment:
      <<: *common-env
    deploy:
      resources:
        limits:
          memory: 500M
    networks:
      - internal-services
      - o8ogss80gkc4k88wkcok8o4c

  transactor:
    image: hardcoreeng/transactor:${HULY_VERSION}
    restart: unless-stopped
    environment:
      <<: *common-env
      SERVER_PORT: 3333
      SERVER_CURSOR_MAXTIMEMS: 30000
      FRONT_URL: "http://localhost:8087"
      FULLTEXT_URL: "http://fulltext:4700"
      LAST_NAME_FIRST: true
    networks:
      - internal-services
      - o8ogss80gkc4k88wkcok8o4c

  collaborator:
    image: hardcoreeng/collaborator:${HULY_VERSION}
    restart: unless-stopped
    environment:
      <<: *common-env
      COLLABORATOR_PORT: 3078
    networks:
      - internal-services
      - o8ogss80gkc4k88wkcok8o4c

  account:
    image: hardcoreeng/account:${HULY_VERSION}
    restart: unless-stopped
    environment:
      <<: *common-env
      SERVER_PORT: 3000
      TRANSACTOR_URL: "ws://transactor:3333;wss://${SERVER_ADDRESS}/ws/transactor"
      FRONT_URL: "http://front:8080"
      MODEL_ENABLED: "*"
      ACCOUNT_PORT: 3000
    networks:
      - internal-services
      - o8ogss80gkc4k88wkcok8o4c

  workspace:
    image: hardcoreeng/workspace:${HULY_VERSION}
    restart: unless-stopped
    environment:
      <<: *common-env
      TRANSACTOR_URL: "ws://transactor:3333;wss://${SERVER_ADDRESS}/ws/transactor"
      MODEL_ENABLED: "*"
    networks:
      - internal-services
      - o8ogss80gkc4k88wkcok8o4c

  # Public / Ingress-Dienste (Projektnetz + Traefik)
  front:
    image: hardcoreeng/front:${HULY_VERSION}
    restart: unless-stopped
    environment:
      <<: *common-env
      SERVER_PORT: 8080
      ACCOUNTS_URL: "https://${SERVER_ADDRESS}/accounts"
      REKONI_URL: "https://${SERVER_ADDRESS}/rekoni"
      CALENDAR_URL: "https://${SERVER_ADDRESS}:8095"
      GMAIL_URL: "https://${SERVER_ADDRESS}:8088"
      TELEGRAM_URL: "https://${SERVER_ADDRESS}:8086"
      STATS_URL: "https://${SERVER_ADDRESS}/stats"
      UPLOAD_URL: /files
      ELASTIC_URL: http://elastic:9200
      COLLABORATOR_URL: "wss://${SERVER_ADDRESS}/ws/collaborator"
      TITLE: Huly Self Host
      DEFAULT_LANGUAGE: en
      LAST_NAME_FIRST: true
      DESKTOP_UPDATES_CHANNEL: selfhost
    networks:
      - o8ogss80gkc4k88wkcok8o4c
      - coolify

  fulltext:
    image: hardcoreeng/fulltext:${HULY_VERSION}
    restart: unless-stopped
    environment:
      <<: *common-env
      FULLTEXT_DB_URL: http://elastic:9200
      ELASTIC_INDEX_NAME: huly_storage_index
      REKONI_URL: http://rekoni:4004
    networks:
      - internal-services
      - o8ogss80gkc4k88wkcok8o4c

  stats:
    image: hardcoreeng/stats:${HULY_VERSION}
    restart: unless-stopped
    environment:
      <<: *common-env
      PORT: 4900
    networks:
      - o8ogss80gkc4k88wkcok8o4c
      - coolify

volumes:
  db:
  elastic:
  files:

networks:
  internal-services:
    external: true
  o8ogss80gkc4k88wkcok8o4c:
    external: true
  coolify:
    external: true
