version: "3.8"

x-common-env: &common-env
  SERVER_SECRET: ${HULY_SECRET}
  SECRET: ${HULY_SECRET}
  STORAGE_CONFIG: minio|minio?accessKey=minioadmin&secretKey=minioadmin
  MONGO_URL: mongodb://mongodb:27017
  DB_URL: mongodb://mongodb:27017
  ACCOUNTS_URL: http://account:3000
  STATS_URL: http://stats:4900

services:
  # ------------------------------
  # 1. Backend-Datenbank (intern)
  # ------------------------------
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb-o8ogss80gkc4k88wkcok8o4c-200110616830
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - COOLIFY_BRANCH="main"
      - COOLIFY_RESOURCE_UUID=o8ogss80gkc4k88wkcok8o4c
      - COOLIFY_CONTAINER_NAME=mongodb-o8ogss80gkc4k88wkcok8o4c-200110616830
    volumes:
      - o8ogss80gkc4k88wkcok8o4c_db:/data/db
    networks:
      - internal-services

  # ------------------------------
  # 2. Backend-Object-Storage (intern)
  # ------------------------------
  minio:
    image: minio/minio:RELEASE.2025-05-01T00-00-00Z
    container_name: minio-o8ogss80gkc4k88wkcok8o4c-200110620716
    restart: unless-stopped
    command: server /data --address ":9000" --console-address ":9001"
    environment:
      - COOLIFY_BRANCH="main"
      - COOLIFY_RESOURCE_UUID=o8ogss80gkc4k88wkcok8o4c
      - COOLIFY_CONTAINER_NAME=minio-o8ogss80gkc4k88wkcok8o4c-200110620716
    volumes:
      - o8ogss80gkc4k88wkcok8o4c_files:/data
    networks:
      - internal-services

  # ------------------------------
  # 3. Backend-Such-Cluster (intern)
  # ------------------------------
  elastic:
    image: elasticsearch:7.14.2
    container_name: elastic-o8ogss80gkc4k88wkcok8o4c-200110623074
    restart: unless-stopped
    command: |
      ./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment
      /usr/local/bin/docker-entrypoint.sh eswrapper
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8082
      - COOLIFY_BRANCH="main"
      - COOLIFY_RESOURCE_UUID=o8ogss80gkc4k88wkcok8o4c
      - COOLIFY_CONTAINER_NAME=elastic-o8ogss80gkc4k88wkcok8o4c-200110623074
    volumes:
      - o8ogss80gkc4k88wkcok8o4c_elastic:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL","curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"red\"'"]
      interval: 20s
      retries: 10
    networks:
      - internal-services

  # --------------------------------------
  # 4. Business-Logik / Worker (intern + proj)
  # --------------------------------------
  rekoni:
    image: hardcoreeng/rekoni-service:${HULY_VERSION}
    container_name: rekoni-o8ogss80gkc4k88wkcok8o4c-200110625666
    restart: unless-stopped
    environment:
      <<: *common-env
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: o8ogss80gkc4k88wkcok8o4c
      COOLIFY_CONTAINER_NAME: rekoni-o8ogss80gkc4k88wkcok8o4c-200110625666
      COOLIFY_URL: https://rekoni.work.illunade.de
      COOLIFY_FQDN: rekoni.work.illunade.de
    deploy:
      resources:
        limits:
          memory: 500M
    networks:
      - internal-services
      - o8ogss80gkc4k88wkcok8o4c

  transactor:
    image: hardcoreeng/transactor:${HULY_VERSION}
    container_name: transactor-o8ogss80gkc4k88wkcok8o4c-200110629239
    restart: unless-stopped
    environment:
      <<: *common-env
      SERVER_PORT: 3333
      SERVER_CURSOR_MAXTIMEMS: 30000
      FRONT_URL: "http://localhost:8087"
      FULLTEXT_URL: "http://fulltext:4700"
      LAST_NAME_FIRST: true
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: o8ogss80gkc4k88wkcok8o4c
      COOLIFY_CONTAINER_NAME: transactor-o8ogss80gkc4k88wkcok8o4c-200110629239
      COOLIFY_URL: https://transactor.work.illunade.de
      COOLIFY_FQDN: transactor.work.illunade.de
    networks:
      - internal-services
      - o8ogss80gkc4k88wkcok8o4c

  collaborator:
    image: hardcoreeng/collaborator:${HULY_VERSION}
    container_name: collaborator-o8ogss80gkc4k88wkcok8o4c-200110632313
    restart: unless-stopped
    environment:
      <<: *common-env
      COLLABORATOR_PORT: 3078
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: o8ogss80gkc4k88wkcok8o4c
      COOLIFY_CONTAINER_NAME: collaborator-o8ogss80gkc4k88wkcok8o4c-200110632313
      COOLIFY_URL: https://collaborator.work.illunade.de
      COOLIFY_FQDN: collaborator.work.illunade.de
    networks:
      - internal-services
      - o8ogss80gkc4k88wkcok8o4c

  account:
    image: hardcoreeng/account:${HULY_VERSION}
    container_name: account-o8ogss80gkc4k88wkcok8o4c-200110635342
    restart: unless-stopped
    environment:
      <<: *common-env
      SERVER_PORT: 3000
      TRANSACTOR_URL: "ws://transactor:3333;wss://${SERVER_ADDRESS}/ws/transactor"
      FRONT_URL: "http://front:8080"
      MODEL_ENABLED: "*"
      ACCOUNT_PORT: 3000
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: o8ogss80gkc4k88wkcok8o4c
      COOLIFY_CONTAINER_NAME: account-o8ogss80gkc4k88wkcok8o4c-200110635342
      COOLIFY_URL: https://account.work.illunade.de
      COOLIFY_FQDN: account.work.illunade.de
    networks:
      - internal-services
      - o8ogss80gkc4k88wkcok8o4c

  workspace:
    image: hardcoreeng/workspace:${HULY_VERSION}
    container_name: workspace-o8ogss80gkc4k88wkcok8o4c-200110638531
    restart: unless-stopped
    environment:
      <<: *common-env
      TRANSACTOR_URL: "ws://transactor:3333;wss://${SERVER_ADDRESS}/ws/transactor"
      MODEL_ENABLED: "*"
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: o8ogss80gkc4k88wkcok8o4c
      COOLIFY_CONTAINER_NAME: workspace-o8ogss80gkc4k88wkcok8o4c-200110638531
    networks:
      - internal-services
      - o8ogss80gkc4k88wkcok8o4c

  # --------------------------------------
  # 5. Public/Ingress-Dienste (proj + ingress)
  # --------------------------------------
  front:
    image: hardcoreeng/front:${HULY_VERSION}
    container_name: front-o8ogss80gkc4k88wkcok8o4c-200110641830
    restart: unless-stopped
    environment:
      <<: *common-env
      SERVER_PORT: 8080
      ACCOUNTS_URL: "https://${SERVER_ADDRESS}/accounts"
      REKONI_URL: "https://${SERVER_ADDRESS}/rekoni"
      CALENDAR_URL: "https://${SERVER_ADDRESS}:8095"
      GMAIL_URL: "https://${SERVER_ADDRESS}:8088"
      TELEGRAM_URL: "https://${SERVER_ADDRESS}:8086"
      STATS_URL: "https://${SERVER_ADDRESS}/stats"
      UPLOAD_URL: /files
      ELASTIC_URL: http://elastic:9200
      COLLABORATOR_URL: "wss://${SERVER_ADDRESS}/ws/collaborator"
      TITLE: Huly Self Host
      DEFAULT_LANGUAGE: en
      LAST_NAME_FIRST: true
      DESKTOP_UPDATES_CHANNEL: selfhost
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: o8ogss80gkc4k88wkcok8o4c
      COOLIFY_CONTAINER_NAME: front-o8ogss80gkc4k88wkcok8o4c-200110641830
      COOLIFY_URL: https://work.illunade.de
      COOLIFY_FQDN: work.illunade.de
    networks:
      - o8ogss80gkc4k88wkcok8o4c
      - coolify

  fulltext:
    image: hardcoreeng/fulltext:${HULY_VERSION}
    container_name: fulltext-o8ogss80gkc4k88wkcok8o4c-200110645020
    restart: unless-stopped
    environment:
      <<: *common-env
      FULLTEXT_DB_URL: http://elastic:9200
      ELASTIC_INDEX_NAME: huly_storage_index
      REKONI_URL: http://rekoni:4004
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: o8ogss80gkc4k88wkcok8o4c
      COOLIFY_CONTAINER_NAME: fulltext-o8ogss80gkc4k88wkcok8o4c-200110645020
    networks:
      - internal-services
      - o8ogss80gkc4k88wkcok8o4c

  stats:
    image: hardcoreeng/stats:${HULY_VERSION}
    container_name: stats-o8ogss80gkc4k88wkcok8o4c-200110647816
    restart: unless-stopped
    environment:
      <<: *common-env
      PORT: 4900
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: o8ogss80gkc4k88wkcok8o4c
      COOLIFY_CONTAINER_NAME: stats-o8ogss80gkc4k88wkcok8o4c-200110647816
      COOLIFY_URL: https://stats.work.illunade.de
      COOLIFY_FQDN: stats.work.illunade.de
    networks:
      - o8ogss80gkc4k88wkcok8o4c
      - coolify

volumes:
  o8ogss80gkc4k88wkcok8o4c_db:
  o8ogss80gkc4k88wkcok8o4c_files:
  o8ogss80gkc4k88wkcok8o4c_elastic:

networks:
  internal-services:
    external: true
  o8ogss80gkc4k88wkcok8o4c:
    external: true
  coolify:
    external: true
